From node:20-alpine AS base
WORKDIR /app
COPY package*.json ./

# devlopemnt target
FROM base AS development
ENV NODE_ENV=development
RUN npm install
COPY . .
EXPOSE 4000
CMD ["npm", "run", "dev"]


# For PROD Only
FROM base AS dependencies
ENV NODE_ENV=production
RUN npm ci --omit=dev


# production target
FROM node:20-alpine AS production
WORKDIR /app
ENV NODE_ENV=production
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
COPY --from=dependencies /app/node_modules ./node_modules
COPY package*.json ./
COPY . .
USER appuser
EXPOSE 4000
CMD ["node", "src/index.js"]